#!/bin/bash
#
# chkconfig: 35 90 12
# description: rsstorrent
#

# Get function from functions library
. /etc/init.d/functions

# Start the service
start() {
        initlog -c "echo -n Starting rsstorrent service: "
        /path/to/rsstorrent &
        ### Create the lock file ###
        touch /var/lock/subsys/rsstorrent
        success $"rsstorrent server startup"
        echo
}

# Restart the service rsstorrent
stop() {
        initlog -c "echo -n Stopping rsstorrent server: "
        killproc rsstorrent
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/rsstorrent
        echo
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status rsstorrent
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
